In [14]:
import numpy as np



In [18]:
import numpy as np

a=[1,2,3,4,5,6]
a
type(a)


list

In [19]:
#creating array from list
x=np.array(a)
x
type(x)


numpy.ndarray

In [20]:
a=np.array([[1,2,3,],[4,5,6]])
a



array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# shape attribute--return shape of an array
a.shape


(2, 3)

In [22]:
#size --return total number of elements in an array
a.size


6

In [23]:
#ndim --gives how many dimension of an array
a.ndim

2

In [24]:
#transpose -- convert rows into columns and viz
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
#function :1.reshape--change shape of an array ,make sure product should be equal to original array 
a=a.reshape(2,3)
a


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b=np.array([11,12,13,14,15,16])
b=b.reshape(2,3)
b

array([[11, 12, 13],
       [14, 15, 16]])

In [27]:
#2.concatenate -- join two array
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [28]:
#vstack --join two array vertically
np.vstack((a,b))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [29]:
#hstack --join two array horizontally(row)
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [30]:
#append --used to add elemention an array at end
c=np.array([21,22,23,25,26])
c=np.append(c,[27,28,29,30])  # c is an array to be updated ,[array values]

c

array([21, 22, 23, 25, 26, 27, 28, 29, 30])

In [31]:
# insert -- add ele at specified index
c=np.insert(c,3,24) # which array at what index ,which value
c
c=np.insert(c,9,30)
c

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30])

In [32]:
#delete -- delete an ele from array
c=np.delete(c,[9])
c=np.delete(c,[3])
c

array([21, 22, 23, 25, 26, 27, 28, 29, 30])

In [61]:
#arrange -- it create an array with given size
# slicing single dim array
#x=np.arange(6) # 0 to n-1, 0 to 5
#x             #[0,1,2,3,4,5]
y=np.arange(2,30,2)  # 2 to 20 with diff of 4
y
y=y.reshape(7,2)
y
y[0:4]  # lower limit to upper limit -1


array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [34]:
#np.random.rand(4) #1D array with 4 elements 
#np.random.rand(2,3) #2D array with 2 rows and 3 col
#np.random.rand(2,2,3) #3D array with 2 matirx of 2 rows and 3 cols
np.random.randn(2,2,3)

array([[[ 0.79431253, -1.15679192,  0.02831881],
        [-0.44526058,  0.66542449, -0.69574748]],

       [[ 1.74125749, -0.13903828,  2.33779455],
        [ 0.07023992,  1.85611707, -0.73189737]]])

In [35]:
# aggregate function
a=np.arange(1,11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
#sum-- sum of 
a.sum()
print(a.sum())

55


In [41]:
#mean -- find the mean value from all elements
a.mean()
print(a.mean())



5.5


In [46]:
#std-- dinf standard deviation from all values
b=np.arange(2,22,2)
b=b.reshape(2,5)
print(b)

b.std
print(b.std())


[[ 2  4  6  8 10]
 [12 14 16 18 20]]
5.744562646538029


In [45]:
#var-- find variance from all elements
b.var()
print(b.var())



33.0


In [44]:
a.prod()
print(a.prod())



3628800


In [47]:
#min, max find max and min from all matrix
print(b.min())
print(b.max())


2
20


In [49]:
#all checks if all array elements along given evaluate
print(b)
b.all()
print(b.all())


[[ 2  4  6  8 10]
 [12 14 16 18 20]]
True


In [50]:
#zero (rows,col)-- create matrix with 10 by 10 with all zeros
b=np.zeros((10,10))
b
b.all()
print(b.all())


False


In [51]:
#eye (row,col,k=+1/-1/0)-- create diagonal matrix filled with 1 at kth  location
#any()-- checks if any array elements along a given axis evaluate to true
c=np.eye(3)
c.any()
print(c.any())

True


In [54]:
d=np.eye(3,5,k=-1) #k=-1,k=1
d
print(d)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [58]:
b=np.zeros((10,10))

b1=b.shape[1] #how many values in the index 1 or row 1
print(b1)
for i in range(10):
    b[i]=i
    
b    
print(b)

10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [62]:
#cumsum()--returns the cumulative sum of the elements along a given axis
b=np.arange(2,22,2)
b=b.reshape(2,5)
print(b)
b.cumsum() #2+4+6+8+10+12+14---



[[ 2  4  6  8 10]
 [12 14 16 18 20]]


array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [63]:
#cumprod-- returns the cumulative product of the elements along a given axis
b.cumprod()


array([         2,          8,         48,        384,       3840,
            46080,     645120,   10321920,  185794560, 3715891200])

In [64]:
array1=np.array([1,2,3,4,5])
number=10
result=array1+number
print(result)
print(type(result))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [65]:
#vectorisation
array1 = np.array([1, 2, 3, 4, 5 ])
number = 10

#  number sums up with each array element
result = array1 + number

print(result)
print(type(result))


[11 12 13 14 15]
<class 'numpy.ndarray'>


In [67]:
#vectoriastion is used because it takes less time then loop 
# find square of number in an array
import time
start_time= time.time()
def find_square(x):
    if x < 0:
        return 0
    else:
        return x ** 2


#s=find_square(4)
#s
array1 = [1, 2, 3, 4, 5]
v_func=np.vectorize(find_square)
s=v_func(array1)

print(s)

end_time= time.time()

print("total execution time is",end_time-start_time)


[ 1  4  9 16 25]
total execution time is 0.007269620895385742


In [69]:
#broadcasting = we can perform mathematical operations on array of diff shapes . an array with a smaller is expanded to match the shape of a large
array1= np.array([1,2,3])
array2=np.array([[1],[2],[3]])
#print(array2)

sum= array1+ array2
print(sum)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
b=5
c=a+b

In [2]:
#campatibility rules: one of them has a length of 1 or they are equal
#check from right to left
x=np.arange(2,22,2)

#print(x)

y=np.arange(30,40)

w=np.arange(2)

x=x.reshape(2,5)

#y=y.reshape(5,2)  # cannot broadcast
#y=y.reshape(10,1)  # cannot broadcast
y=y.reshape(2,5)

#w=w.reshape(1,2)  #cannot broadcast
w=w.reshape(2,1)
print(w)
z=x+y+w
z

[[0]
 [1]]


array([[32, 35, 38, 41, 44],
       [48, 51, 54, 57, 60]])

In [7]:
a=np.array([[10,20,30],[40,50,60]])
a
#broadcasting with scalar
b=5
c=a+b
c

array([[15, 25, 35],
       [45, 55, 65]])

In [19]:
#boolean indexing allows us to filter elements from an array based on specific condition
import numpy as np 
a=np.array([23,56,88,1,2,4,10,15])
# boolean mask
bm=a>40
print(bm)
print(a[bm]) #accessing values in an array-->array name[index]

[False  True  True False False False False False]
[56 88]


In [20]:
# use boolean index to select even number from list
bm1=(a%2==0)
print(bm1)
print(a[bm1])

[False  True  True False  True  True  True False]
[56 88  2  4 10]


In [21]:
bm2=(a%2==0)&(a>40)  # even number greater than 40
print(bm2)
print(a[bm2])

[False  True  True False False False False False]
[56 88]


In [12]:
 # logical AND ,OR
#update the true value with specified value
a[a%2==0]=100
a

array([ 23, 100, 100,   1, 100, 100, 100,  15])

In [13]:
# create a 2D  array
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

# create a boolean mask based on the condition 
# that elements are greater than 9
boolean_mask = array1 > 9

# select only the elements that satisfy the condition
result = array1[boolean_mask]

print(result)
print(boolean_mask)

[14 19 21 25 29 35]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# update the true value with specified value
a[bm2]=100
a

array([ 23, 100, 100,   1, 100, 100, 100,  15])